export interface NewUser {
    name: string;
    email: string;
    password: string;
    image_url?: string;
}

export interface User extends NewUser {
    id: string; // v4 UUID autogenerated by database
    is_verified: boolean;
    created_at: string;
    updated_at: string;
}

export interface NewHousehold {
    name: string;
    owner_id: User["id"];
}

export interface Household extends NewHousehold {
    id: string; // v4 UUID autogenerated by database
    created_at: string;
    updated_at: string;
}

export interface UserHousehold {
    user_id: User["id"];
    household_id: Household["id"];
}

export interface NewPet {
    name: string;
    species: string;
    birthdate: string;
    image_url?: string;
    weight: number;
    household_id: Household["id"];
}

export interface Pet extends NewPet {
    id: string; // v4 UUID autogenerated by database
    created_at: string;
    updated_at: string;
}

export interface DosageUnit {
    id: string; // v4 UUID autogenerated by database
    name: string;
}

export interface NewMedication {
    name: string;
    pet_id: Pet["id"];
    dosage_amount: string;
    dosage_unit: DosageUnit["id"];
    start_date?: string;
    end_date?: string;
    notes?: string;
}

export interface Medication extends NewMedication {
    id: string; // v4 UUID autogenerated by database
    created_at: string;
    updated_at: string;
}

export interface NewMedicationSchedule {
    scheduled_time: string;
    medication_id: Medication["id"];
}

export interface MedicationSchedule extends NewMedicationSchedule {
    id: string; // v4 UUID autogenerated by database
    created_at: string;
    updated_at: string;
}

export interface NewMedicationLog {
    medication_id: Medication["id"];
    scheduled_medication_id: MedicationSchedule["id"];
    administering_user_id: User["id"];
    administration_time: string;
}

export interface MedicationLog extends NewMedicationLog {
    id: string; // v4 UUID autogenerated by database
    time_logged: string; // The insertion timestamp to serve as an audit log
}
